[project]
name = "autumoodle"
version = "0.1.0"
description = "Download and organize course materials from TUM Moodle"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "httpx>=0.28.1",
    "playwright>=1.55.0",
]
