name: autumoodle

services:
  autumoodle:
    image: ghcr.io/uyanide/autumoodle:latest
    # build:
    #   context: ../
    # command: ['-t', 'NeverGonnaGiveYouUp'] # prevent download for testing
    env_file:
      - .env
    container_name: autumoodle
    volumes:
      - /home/kolkas/Documents/Uni:/data
      - /home/kolkas/.cache/autumoodle:/cache
      - /home/kolkas/Repositories/AuTUMoodle/config/config-docker.json:/app/config.json:ro
